spring.application.name=inventory-service
server.port=8082

# Banco PRÓPRIO do Inventory (Database per Service)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/inventory_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
